migrate scale web role to centos8
socallinuxexpo/scale-chef pull request #283
Opened 2023-09-15 23:37 UTC by irabinovitch

### What does this PR do?

update apache and drupal cookbooks for centos8

### Motivation

Newer is always better?

### Testing Guidelines

spin up a centos8 vm or vagrant, run it with role[web]

### Additional Notes

- Drush's official docs suggest we should be installing via composer or in our drupal code base rather than via rpm. I've skipped it for now.

- Centos8 seems to default to using php-fpm instead of mod_php.  Seems to work fine, but seemed like something to call out.

2023-09-18 10:38 UTC, davide125 requested changes

2023-09-18 10:38 UTC, davide125 commented on cookbooks/scale_apache/recipes/default.rb
> +end
Consolidate copypasta and future proof
```suggestion
pkgs = %w{
  git
  php
  php-gd
  php-mysql
  php-pdo
  php-xml
  php-mbstring
}
if node.centos7?
  pkgs << 'python2-boto'
else
  pkgs << 'python3-boto3'
end
```

2023-09-18 10:38 UTC, davide125 commented on cookbooks/scale_drupal/recipes/default.rb
>  end
Future proof

```suggestion
package 'drush' do
  only_if { node.centos7? }
  action :upgrade
end

package 'awscli' do
  not_if { node.centos7? }
  action :upgrade
end
```

2023-09-22 23:17 UTC, jaymzh commented on cookbooks/scale_drupal/recipes/default.rb
> +  end
I'd really love to DRY all this up.
```ruby
# new stuff is py3
restore_source = 'restore-drupal-static3.py.erb'
backup_source = 'backupdrupal-static3.py.erb'

# support for our older OSes...
if node.centos6? || node.centos7?
  restore_source = 'restore-drupal-static.py.erb'
  backup_source = 'backupdrupal-static.py.erb'
end

template '/usr/local/bin/backup-drupal-static.sh' do
  owner 'root'
  group 'root'
  mode '0755'
  source backup_source
end

template '/usr/local/bin/restore-drupal-static.py' do
  owner 'root'
  group 'root'
  mode '0755'
  source restore_source
end
```

2023-09-25 08:08 UTC, jaymzh commented on scripts/setup_dev.sh
> -echo "Checking for CINC version of Chef Workstation"
Why remove this?

2023-09-26 16:10 UTC, jaymzh approved these changes

2023-09-27 02:24 UTC, merged